---
services: docker

script:
  # Test building Dockerfile.
  - docker build -t debian9-slim .

  # Test running the container.
  - docker run --name debian9-slim -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro debian9-slim

  # Verify packages in the container.
  - docker exec --tty debian9-slim env TERM=xterm dpkg-query -W -f='${Status} ${Package} ${Version} ${Architecture}\n'|awk '($1 == "install") && ($2 == "ok") {print $4" "$5" "$6}'

  - docker push docker.io/cleveritcz/debian9-slim
